export const ADD_INGRIDIENT = 'ADD_INGRIDIENT';
export const SUB_INGRIDIENT = 'SUB_INGRIDIENT';
export const REMOVE_CLICKED_INGRIDIENT = 'REMOVE_CLICKED_INGRIDIENT';
export const RESET_WHOLE_STATE = 'RESET_WHOLE_STATE';
export const FETCH_INIT_INGRIDIENTS = 'FETCH_INIT_INGRIDIENTS';
export const FETCH_INIT_INGRIDIENTS_ERROR = 'FETCH_INIT_INGRIDIENTS_ERROR';

export const POST_ORDER_DATA = 'POST_ORDER_DATA';
export const POST_ORDER_DATA_ERROR = "POST_ORDER_DATA_ERROR";
export const POST_ORDER_DATA_START = 'POST_ORDER_DATA_START';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';
export const LOADING_ORDERS = 'LOADING_ORDERS';
export const DELETE_ORDER = 'DELETE_ORDER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const LOGOUT = 'LOGOUT';

export const AUTO_LOGIN = 'AUTO_LOGIN';
